### ISSUE TITLE
Updating instructions for nvidia-docker 2

### ISSUE THREAD

**Issue by jakirkham** [MMathisLab/Docker4DeepLabCut2.0#1]
Recent versions of NVIDIA's Docker support integrate more smoothly with unpatched versions of Docker thanks to the fact that the Docker ecosystem has been opened up a bit and has been split more cleanly into different components serving different purposes. Given this, it would be nice to upgrade the instructions here to work with these newer versions of Docker. This may make it easier for users less immersed in the Docker ecosystem to get started pretty quickly with containers leveraging GPU support. Details about what this entails in the NVIDIA blog post below.

ref: https://devblogs.nvidia.com/gpu-containers-runtime/

**Comment by MMathisLab** [comment]
agreed! If you have suggestions, I'd be happy for your PR :)

**Comment by neuropil** [comment]
Hello!
I'm having difficulty getting the Nvidia docker installed on Ubuntu - is there a user group for DeepLabCut for trouble-shooting?

Thanks!
John

**Comment by MMathisLab** [comment]
There is! Send me an email to join the slack (mackenzie@post.harvard.edu)

**Comment by MMathisLab** [comment]
nvidia-docker2 is fully supported. You can install either version 1 or 2, and the install and use instructions are the same.

**Comment by neuropil** [comment]
thanks for the update!

**Comment by ambareeshsrja16** [comment]
With nvidia-docker2 is there something we need to change in the docker file?

**Comment by MMathisLab** [comment]
nope, will work as is.
