### ISSUE TITLE
Docker not building

### ISSUE THREAD

**Issue by auesro** [MMathisLab/Docker4DeepLabCut2.0#10]
Dear Mackenzie,

I had to reinstall Ubuntu from scratch (nothing related to Deeplabcut) but now, reinstalling Deeplabcut's docker ran into this:

![screenshot from 2019-02-09 11-31-42](https://user-images.githubusercontent.com/24290290/52519628-90d5f600-2c5e-11e9-9a05-8541c40d7363.png)

Any suggestions?

**Comment by MMathisLab** [comment]
seems with some versions this error occurs (I can't reproduce it locally), but PR #8 provides a fix!
