### ISSUE TITLE
 Docker container exits instantly when run - manually update CUDA?

### ISSUE THREAD

**Issue by dehmelt** [MMathisLab/Docker4DeepLabCut2.0#11]
_I accidentally posted this [here](https://github.com/AlexEMG/Docker4DeepLabCut/issues/7) yesterday, but it is in fact an issue I encountered with the Docker for DLC2. My apologies for the confusion!_

**Error:**
Docker container appears to exit instantly when run. Thus, cannot enter container normally via 
`GPU=0 bash ./dlc-docker run (...)`. Crash may be caused by wrong CUDA version for our GPU.

Issue appears similar to [this](https://github.com/AlexEMG/Docker4DeepLabCut/issues/2) for DLC1 or https://github.com/MMathisLab/Docker4DeepLabCut2.0/issues/5 for DLC2, but isn't resolved by adjusting the home directory. My chosen home directory _does_ already exist, and is empty.

**Server configuration:**
Docker: version 18.09.1, build 4c52b90
GPUs: 2 x NVIDIA GeForce RTX 2080
GPU driver: version 410.79
CUDA: 10.0

**Comments:**
Our GPU [might require CUDA 10.0](https://towardsdatascience.com/how-to-make-tensorflow-work-on-rtx-20xx-series-73eb409bd3c0) (as indeed installed on our server), instead of CUDA 9.0 (as present within the container for DLC2). _Can I manually update CUDA, cuDNN and/or the GPU drivers within the container?_

**Steps to reproduce:**

1. Connected to server, `ssh -X %SERVERNAME`. Verified that docker is installed, as well as `docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi`, which downloaded a newer image. (Later repeated the entire process for 10.0, since that's the version installed on our server, with identical results.)

2. Created desired home directory, `mkdir $HOME/DeepLabCut`, then `mkdir $HOME/DeepLabCut/DeepHome`.

3. From within $HOME/DeepLabCut, successfully cloned, `git clone https://github.com/MMathisLab/Docker4DeepLabCut2.0`.

4. From within $HOME/DeepLabCut/Docker4DeepLabCut2.0, successfully built image, `docker image build -t $DLCUSER/deepdock .` My chosen $DLCUSER is different from my user name on the network, $NETWORKUSER.

5. Attempted to run container, `GPU=0 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut/DeepHome --name deepdock $DLCUSER/deepdock`. 

6. `docker ps -a` confirms that the container exited instantly:
```
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                     PORTS               NAMES
3666b6cbee76        $DLCUSER/deepdock   "/usr/local/bin/entr…"   3 seconds ago       Exited (1) 2 seconds ago                       deepdock
```

7. Trying to enter the container via `docker exec --user $DLCUSER -it deepdock /bin/bash` returns the expected error: `Error response from daemon: Container fbe0ff45cbb21225dcf51c88b157e1e0b40fd0e8d4bce7b69a4a9f53d1c54594 is not running`.

**Comment by MMathisLab** [comment]
I'm a bit confused on this part:

`Created desired home directory, mkdir $HOME/DeepLabCut, then mkdir $HOME/DeepLabCut/DeepHome.`

I assume you made a directory like this:

`mkdir DeepLabCut` (not like$HOME/DeepLabCut?) 

The error also appears here, as you have no port listed. Perhaps if you created the DeepLabCut folder incorrectly it cannot bind properly so no port is set up.

Attempted to run container, GPU=0 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut/DeepHome --name deepdock $DLCUSER/deepdock.

docker ps -a confirms that the container exited instantly:

CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                     PORTS               NAMES
3666b6cbee76        $DLCUSER/deepdock   "/usr/local/bin/entr…"   3 seconds ago       Exited (1) 2 seconds ago                       deepdock


You likely have to change the Docker file then to match the @DLCUSER vs just USER (but I assume you did this?)

**Comment by MMathisLab** [comment]
separate issue, but re: 

> Comments:
> Our GPU might require CUDA 10.0 (as indeed installed on our server), instead of CUDA 9.0 (as present within the container for DLC2). Can I manually update CUDA, cuDNN and/or the GPU drivers within the container?

No, you don't need to update anything inside the Container, it will run CUDA 9 just fine even if the server has CUDA 10. The Docker has it's own operating system Ubuntu 16.04 LTS even ;)

**Comment by MMathisLab** [comment]
closed due to inactivity.

**Comment by dehmelt** [comment]
Thanks a lot for your input!

Above, I did provide potentially confusing pseudocode: "$DLCUSER" was just meant as a placeholder for any user name, e.g. "myusername", so `GPU=0 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut/DeepHome --name deepdock **$DLCUSER/deepdock** ."` was meant to stand in, e.g., for `GPU=0 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut/DeepHome --name mycontainername **myusername/mycontainername** ."` So I did **not** in fact enter a $ before the user name.

I'm not sure I understood you comment regarding a missing port, but I have no manually recreated all folders as you suggested (individual calls to mkdir from within the respectove parent directories), cloned again, built the image again, run the container again, and still encounter the same problem (container exits instantly).

Running the container without manually setting a port also yields the same result.

If I understand correctly, this could mean the container is in fact _crashing_ instantly, possibly because of issues with the entrypoint? I'm fairly new to docker, so I'm unsure how to debug this.

**Comment by dehmelt** [comment]
Just to confirm, it was indeed a **basic Docker issue**, unrelated to DeepLabCut. I had been executing the container with, e.g., `GPU=0 bash ./dlc-docker run -d -p 1234:8888 -e USER_HOME=$HOME/DeepLabCut/DeepHome --name containername imageusername/imagecontainername.`

where I had mistakenly specified the path server folder _to be mounted_, `$HOME/DeepLabCut/DeepHome`, instead of the home folder inside the container. As Docker couldn't find the path in question, the container crashed immediately.

**Solution:** Used the **-v or --mount flag**, as in `GPU=1 bash ./dlc-docker run -d -p 1234:8888 -e USER_HOME=/DeepHome -v $HOME/DeepLabCut/DeepHome:/DeepHome --name containername imageusername/imagecontainername .`

where `USER_HOME=/DeepHome` as well as `:/DeepHome` now refer to a folder inside the container (as it should be), and `$HOME/DeepLabCut/DeepHome` refers to the folder on our server to be mounted.
