### ISSUE TITLE
ModuleError

### ISSUE THREAD

**Issue by waseemabbas05** [MMathisLab/Docker4DeepLabCut2.0#12]
Hi
I followed all the steps for pulling the image, building it and then starting it. I started the docker, passed appropriate ports and initiated ipython kernel, but when I tried to import deeplabcut, I encountered the following error
In [1]: import deeplabcut
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-52d2df9c7fa5> in <module>()
----> 1 import deeplabcut

/usr/local/lib/python3.6/dist-packages/deeplabcut/__init__.py in <module>()
     31 else:
     32     mpl.use('TkAgg')
---> 33     from deeplabcut import generate_training_dataset
     34     from deeplabcut import refine_training_dataset
     35 

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/__init__.py in <module>()
     13     pass
     14 else:
---> 15     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
     16     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     17     from deeplabcut.generate_training_dataset.frame_extraction_toolbox import *

/usr/local/lib/python3.6/dist-packages/deeplabcut/generate_training_dataset/auxfun_drag_label.py in <module>()
     16 
     17 import numpy as np
---> 18 import wx
     19 
     20 class DraggablePoint:

ModuleNotFoundError: No module named 'wx

help .......

**Comment by waseemabbas05** [comment]
never mind, found the issue

**Comment by MMathisLab** [comment]
Likely needed to export DLClight = True :)
