### ISSUE TITLE
conda environment and the docker

### ISSUE THREAD

**Issue by JohnCraigPublic** [MMathisLab/Docker4DeepLabCut2.0#13]
Pretty new to Linux and Docker, so bear with me....  For installation of DeepLabCut I have set up an environment (called DLC), and all works great just using CPU.  Now, plugged in new GPU and am trying to use your docker to get training with GPU going.

When I built the image of the docker, should I have been in my DLC environment?  I wasn't, and now I'm wondering...    

Can I start the docker container, then enter my environment, or vice-versa? 

Hope my question make sense.  Be gentle with me.

**Comment by MMathisLab** [comment]
Hey John, good questions, no worries ;)

So, you do not need to be inside conda to instal/use Docker (actually better NOT to be). 

What you can do is use two different terminals to work back and forth, i.e. if you need GUIs, work in anaconda. If you want to train, evaluate, or analysis videos, use Docker. 

Here is a demo of how I do this: https://www.youtube.com/watch?v=7xwOhUcIGio (part 1)
https://www.youtube.com/watch?v=bgfnz1wtlpo (part 2)

**Comment by JohnCraigPublic** [comment]
Thanks Mackenzie -- its all making sense.  My current issue: I don't understand the bit about "creating a docker group" and "add your current user to the group" -- I think I've followed those instructions, but I see now that a lot of files and folders say they are owned by "docker" and I'm not allowed to edit them.  How do I get past this?

**Comment by MMathisLab** [comment]
that should not be the case, as we didn't change permissions by creating the group...but easy to fix/check. You can add yourself to sudo, etc as well, if you are not. 

TO check groups: 
https://vitux.com/how-to-check-the-user-groups-an-ubuntu-user-belongs-to/

to change folder ownership;

https://askubuntu.com/questions/6723/change-folder-permissions-and-ownership

**Comment by JohnCraigPublic** [comment]
OK - all good now - I am training and analyzing on the GPU!  Thanks!
