### ISSUE TITLE
GUI Docker container unable to import deeplabcut in Jupyter notebook because of matplotlib import call

### ISSUE THREAD

**Issue by BenisFarmen** [MMathisLab/Docker4DeepLabCut2.0#14]
Operating system and DeepLabCut version

Please state your operating system, env, and which version of DeepLabCut you are using:
Example: Ubuntu 16.04 LTS, with an Anaconda Env, & DeepLabCut1.x or 2.x.

DeepLabCut GUI Docker on GPU Server (Ubuntu)
Ubuntu 18.04.1 LTS

Describe the problem:

I prepared the server and installed the docker as described in the instructions.

Then I opened a Jupyter Notebook and tried to import deeplabcut, and there it crashes due to an ImportError.

`---------------------------------------------------------------------------
```
ImportError                               Traceback (most recent call last)
<ipython-input-9-63632350fff9> in <module>()
      1 import tensorflow
----> 2 import deeplabcut

/home/ubuntu/anaconda3/lib/python3.6/site-packages/deeplabcut/__init__.py in <module>()
     27     else:
     28         mpl.use('Agg')
---> 29     from deeplabcut import generate_training_dataset
     30     from deeplabcut import refine_training_dataset
     31     from deeplabcut.generate_training_dataset import label_frames, dropannotationfileentriesduetodeletedimages, comparevideolistsanddatafolders

/home/ubuntu/anaconda3/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/__init__.py in <module>()
     17 else:
     18     from deeplabcut.generate_training_dataset.auxfun_drag_label import *
---> 19     from deeplabcut.generate_training_dataset.labeling_toolbox import *
     20     from deeplabcut.generate_training_dataset.frame_extraction_toolbox import *
     21 

/home/ubuntu/anaconda3/lib/python3.6/site-packages/deeplabcut/generate_training_dataset/labeling_toolbox.py in <module>()
     25 import argparse
     26 from deeplabcut.generate_training_dataset import auxfun_drag_label
---> 27 from deeplabcut.utils import auxiliaryfunctions
     28 from matplotlib.backends.backend_wxagg import FigureCanvasWxAgg as FigureCanvas
     29 from matplotlib.backends.backend_wxagg import NavigationToolbar2WxAgg as NavigationToolbar

/home/ubuntu/anaconda3/lib/python3.6/site-packages/deeplabcut/utils/__init__.py in <module>()
----> 1 from deeplabcut.utils.make_labeled_video import *
      2 from deeplabcut.utils.auxiliaryfunctions import *
      3 from deeplabcut.utils.video_processor import *
      4 from deeplabcut.utils.plotting import *
      5 

/home/ubuntu/anaconda3/lib/python3.6/site-packages/deeplabcut/utils/make_labeled_video.py in <module>()
     32     mpl.use('WxAgg') #TkAgg
     33 else:
---> 34     mpl.use('TkAgg')
     35 import matplotlib.pyplot as plt
     36 

/home/ubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/__init__.py in use(arg, warn, force)
   1389         if force:
   1390             from matplotlib.pyplot import switch_backend
-> 1391             switch_backend(name)
   1392     # Finally if pyplot is not imported update both rcParams and
   1393     # rcDefaults so restoring the defaults later with rcdefaults

/home/ubuntu/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py in switch_backend(newbackend)
    220                 "Cannot load backend {!r} which requires the {!r} interactive "
    221                 "framework, as {!r} is currently running".format(
--> 222                     newbackend, required_framework, current_framework))
    223 
    224     rcParams['backend'] = rcParamsDefault['backend'] = newbackend

ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running`
```

**Comment by MMathisLab** [comment]
hi, just pip install matplotlib==3.0.3 then it will be fixed

**Comment by BenisFarmen** [comment]
I ran pip install matplotlib==3.0.3 inside the docker

`ubuntu@70fc75d0d0ea:/work$ pip install matplotlib==3.0.3
Requirement already satisfied: matplotlib==3.0.3 in /home/ubuntu/anaconda3/lib/python3.6/site-packages
Requirement already satisfied: python-dateutil>=2.1 in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.3)
Requirement already satisfied: numpy>=1.10.0 in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.3)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.3)
Requirement already satisfied: cycler>=0.10 in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from matplotlib==3.0.3)
Requirement already satisfied: six>=1.5 in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from python-dateutil>=2.1->matplotlib==3.0.3)
Requirement already satisfied: setuptools in /home/ubuntu/anaconda3/lib/python3.6/site-packages (from kiwisolver>=1.0.1->matplotlib==3.0.3)
`

And when running Jupyter Notebooks afterwards I still get the same error as in the beginning

**Comment by MMathisLab** [comment]
strange... you can run import matplotlib then force the backend:

https://stackoverflow.com/questions/3285193/how-to-switch-backends-in-matplotlib-python
