### ISSUE TITLE
Can not proceed when building the Docker image

### ISSUE THREAD

**Issue by unetzjuser** [MMathisLab/Docker4DeepLabCut2.0#15]
I am trying to install DeepLabCut on a server, but can not build the docker image. When I run the following command from the Dockerfile (docker image build -t dlc_username/dlcdocker .), I always get stuck on Step 5/12 : RUN apt-get update. 

It seems that this package can not be downloaded, but do not know why. I also tried to run it on my computer (Linux Ubuntu 18.04), and encountered the same problem. Your support is highly appreciated.

![图片](https://user-images.githubusercontent.com/52446203/60723237-b1804e80-9f65-11e9-8e33-67d2b4dd24a8.png)

**Comment by MMathisLab** [comment]
You can remove that line from the Docker file if you want; perhaps you don’t have admin rights?

**Comment by unetzjuser** [comment]
I run the commands as the administrator. Now I will delete this line and try again. Thanks for your reply.

**Comment by unetzjuser** [comment]
I run the commands as the administrator. Now I will delete this line and try again. Thanks for your reply.

**Comment by unetzjuser** [comment]
I solved this problem by editing the dockerfile:

Delete RUN apt-get update

Replace RUN apt-get -y install ffmpeg by  RUN pip install ffmpeg

Thank you.
