### ISSUE TITLE
 Ubuntu with GPU Docker: “no matching entries in passwd file”

### ISSUE THREAD

**Issue by alvarovegahd** [MMathisLab/Docker4DeepLabCut2.0#16]
**Describe the bug**

I am running docker in ubuntu 18.04, with a GPU Nvidia. nvidia-. The docker image was built with no errors. When I run 

`GPU=0 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut --name containername dlc_username/dlcdocker`

I get no error message. But when I run:

`docker exec --user $USER -it containername /bin/bash`

I get:

`Error response from daemon: Container b6761d046e4e4e104c2d4bdbaf52528a59bcd171e4f5ca9a652248be05a4248c is not running`

I think the docker exits automatically when I run it. Because when I run the two commands in chain (I have to first remove the container for this), I get an error message:

`unable to find user alvaro: no matching entries in passwd file`

I would appreciate a lot some advice on this.

**Desktop:**
 - OS: Ubuntu 18.04 with GPU Nvidia GTX 1060
 - DeepLabCut Version: the one in the current Docker container repo

**Additional context**
I have never used Docker containers before. [I posted it on image.sc](https://forum.image.sc/t/ubuntu-with-gpu-docker-no-matching-entries-in-passwd-file/27532) but they told me it was not related to image analysis. They suggested to just restart the docker engine, based in [this open bug in Docker](https://success.docker.com/article/ucp-health-checks-fail-unable-to-find-user-nobody-no-matching-entries-in-passwd-file-observed) but it did not work.

**Comment by MMathisLab** [comment]
So you have a folder called /home/DeepLabCut ?

**Comment by alvarovegahd** [comment]
That was the problem. Adding the folder to my home fixed it. Thank you!
