### ISSUE TITLE
docker is not running 

### ISSUE THREAD

**Issue by xcharxlie** [MMathisLab/Docker4DeepLabCut2.0#17]
OS : linux Ubuntu 18.04
NVIDIA driver: 430.26
CUDA 10.1

HI, it's me again. I followed the instructions and met the problem that I could not execute the docker just created. It prompted me that the docker was not running and noted exited. I was trying to restart it but no difference. I am just new to this, thanks for any help in advance.

![Screenshot from 2019-08-09 13-32-37](https://user-images.githubusercontent.com/53882515/62807454-3bae5c00-baaa-11e9-81f9-50b99ca72206.png)

**Comment by MMathisLab** [comment]
do you have a directory called `/home/DeepLabCut` ?

**Comment by xcharxlie** [comment]
I think no. How does it relate?

**Comment by xcharxlie** [comment]
You mean I am supposed to make the docker in a specific file and run the docker in that certain directory?

**Comment by MMathisLab** [comment]
HOME is where you are binding the docker to. So, you have to have a real directory to bind to. 

So, you need to either point to a real folder, or create a new folder in /home/ called DeepLabCut

You should also delete the dead attempts. 

https://github.com/MMathisLab/Docker4DeepLabCut2.0#docker-quick-tips

`docker rm containername`

**Comment by MMathisLab** [comment]
also check out the other issues where this was the same issue, i.e. not correctly binding to HOME: #5 #11

**Comment by xcharxlie** [comment]
Thank you. It helps! But it turns out to this. I have tried pip install wxand sudo apt-get install python-wxtools, but still failed. 
![Screenshot from 2019-08-09 14-54-53](https://user-images.githubusercontent.com/53882515/62811240-dc564900-bab5-11e9-8550-62c7994a941a.png)

**Comment by MMathisLab** [comment]
you cannot use wxPython in the Docker. Please read the readme.md 

https://github.com/MMathisLab/Docker4DeepLabCut2.0#starting-the-docker-container-from-your-image-de-novo


![image](https://user-images.githubusercontent.com/28102185/62811455-b2aa1b80-bacf-11e9-9f00-c24764e4cdc5.png)


Also, please read the user-guide which explains that you should use Docker for training and inference only. 

Also, these video tutorials show you how to do this exactly. 

https://www.youtube.com/watch?v=7xwOhUcIGio

https://www.youtube.com/watch?v=bgfnz1wtlpo
