### ISSUE TITLE
Python 3.6 PPA removed from public access

### ISSUE THREAD

**Issue by kir0ul** [MMathisLab/Docker4DeepLabCut2.0#21]
Hi,

I get the following error when I tried to build the container from the Dockerfile:
```
W: The repository 'http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu xenial Release' does not have a Release file.
E: Failed to fetch http://ppa.launchpad.net/jonathonf/python-3.6/ubuntu/dists/xenial/main/binary-amd64/Packages  404  Not Found
```
Seems that the Python 3.6 PPA has been removed from public access: https://launchpad.net/~jonathonf/+archive/ubuntu/python-3.6

**Comment by kir0ul** [comment]
Seems to work if I modify the Dockerfile like this:
```diff
 RUN pip install imageio-ffmpeg

 FROM bethgelab/deeplearning:cuda9.0-cudnn7
+RUN add-apt-repository --remove ppa:jonathonf/python-3.6
 RUN apt-get update
 RUN apt-get -y install ffmpeg
```

**Comment by lhcamilo** [comment]
I can do one better. I order to make sure that python is installed remove the repository like you proposed and add another. Apparently the maintainer closed the repo in protest. 

Here is how the dockerfile should look like
 
FROM bethgelab/deeplearning:cuda9.0-cudnn7
RUN add-apt-repository ppa:deadsnakes/ppa # ADDS NEW REPO
RUN add-apt-repository --remove ppa:jonathonf/python-3.6 # REMOVES BROKEN REPO
RUN apt-get update
RUN apt-get -y install ffmpeg
`

This image really needs to be updated.

**Comment by MMathisLab** [comment]
^ thanks noticing this! updated, @lhcamilo
