### ISSUE TITLE
Adding High Performance Computing support with Singularity 

### ISSUE THREAD

**Issue by Hanlin-Zhu** [MMathisLab/Docker4DeepLabCut2.0#3]
Dear Deeplabcut Developers,
Hi, I am a user of DeepLabCut who find your software truly astonishing when applied to our mice 
continuous monitoring project! We purchased 3 GPUs to analyzing months-long videos using the docker container you supplied. Unfourtantely, it seem that for our case, the processing speed still lag far behind 
new data generation.

After some research, we find that maybe deploying deeplabcut for video evaluation step only on HPC clusters with GPU/tensorflow support might be the solution. The specific platform that we are considering is Comet Supercomuting systems that support user defined enviroment thorough Singularity. (They offer trial account for ~100GPU hours)
https://www.sdsc.edu/support/user_guides/tutorials/singularity.html     
NIH seems that have a similar system as well  https://hpc.nih.gov/apps/singularity.html

I tried to make a conversion from docker container dlc_username/dlcdocker to Singularity image with 
https://github.com/singularityware/docker2singularity
Detailed Command:
docker run -v /var/run/docker.sock:/var/run/docker.sock \\
-v /home/hanlin:/output \\
--privileged -t --rm \\
singularityware/docker2singularity \\
--name hanlinGPU dlc_username/dlcdocker 
but failed to import deeplabcut inside the singularity image (command: singularity shell hanlinGPU.simg)
(trying on my own desktop, not on HPC yet) with the following erros. 
![image](https://user-images.githubusercontent.com/12913124/51806933-ca156b80-2245-11e9-951c-0418ddc506d5.png)

![image](https://user-images.githubusercontent.com/12913124/51806939-e0bbc280-2245-11e9-97b8-c10f4bd9ff45.png)

The problem might be some " path binding " issues referred in the NIH singularity guide above but I couldn't understand much as being quite new to linux systems. Could you kindly guide me through such conversion.  This should really benefit the research community where high thouroughput analysis is desired.  Thanks a lot! 

Best

**Comment by MMathisLab** [comment]
I have never used singularity, but from the error, Tensorflow is not installed - you might be better served to find a Singularity container with TF installed, then just add DeepLabCut (that should be easier than TF). I know the researchers at Janelia use Singularity for DeepLabCut so maybe @adamltaylor has some tips

**Comment by MMathisLab** [comment]
Otherwise, you can deploy the Docker on AWS

**Comment by Hanlin-Zhu** [comment]
Thanks for the prompt reply! I will check out their GitHub folders for hints.

**Comment by Hanlin-Zhu** [comment]
After reviewing the procedures documented there  https://github.com/JaneliaSciComp/dlc-trainer ,
I found what I did incorrectly. I should have called "singularity shell **--nv** hanlinGPU.simg" to enabled GPU
support for Singularity. I previously called "singularity shell hanlinGPU.simg" resulting the installed tensorflow_gpu-1.8 not being able to be found. 😅
