### ISSUE TITLE
Starting the docker container, error: invalid device: 1

### ISSUE THREAD

**Issue by AdrianChe** [MMathisLab/Docker4DeepLabCut2.0#4]
Hi again, 

Do you know what could be the problem with this error? It appears when I'm trying to start the docker container from image.

Thanks, 

ebfmlab@ebfmlab:~/Docker4DeepLabCut2.0$ GPU=1 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut --name containername dlc_username/dlcdocker
ret run -d -p 2351:8888 -e USER_HOME=/home/ebfmlab/DeepLabCut --name containername dlc_username/dlcdocker run
1st CMD run

* Setting user name to:             ebfmlab
* Setting user ID to:               1000
* Setting user groups to:           sudo
* Setting password to:              pw
* Setting Notebook port binding to: 2351 (to set manually add -p 2351:8888 as flag)

You can now open the notebook on the host machine by directing your browser to

    http://localhost:2351

1 nvidia-docker run -v /home/ebfmlab:/home/ebfmlab -p 51674:22 -p 2351:8888 -e USER_GROUPS=sudo -e USER=ebfmlab -e USER_ID=1000 -e USER_ENCRYPTED_PASSWORD=aa5V9MSdgw5ec -e USER_HOME=/home/ebfmlab -e GPU=1 -d -e USER_HOME=/home/ebfmlab/DeepLabCut --name containername dlc_username/dlcdocker
nvidia-docker | 2019/01/29 21:54:17 Error: invalid device: 1

**Comment by MMathisLab** [comment]
do you have two GPUs on your system? Typically if you just have 1, it is GPU=0. You can get the # from running ``nvidia-smi `` in terminal.

**Comment by AdrianChe** [comment]
Thank you very much, yeah that was the problem.
