### ISSUE TITLE
Contner not running

### ISSUE THREAD

**Issue by AdrianChe** [MMathisLab/Docker4DeepLabCut2.0#5]
Hello,  

Me again sorry I'm totally new at using docker. Each time I want to execute the docker to train the network it says that is not  running.

ebfmlab@ebfmlab:~$ docker exec --user $USER -it containername /bin/bash
Error response from daemon: Container ce856759f3c87888b9e41647094839152b1fdc429354e7989165698524cf2d1d is not running

Best.

**Comment by MMathisLab** [comment]
you should look at `docker ps -a` and see if it is running. Maybe check out some basics for Docker, i.e. https://medium.com/the-andela-way/introduction-to-docker-commands-eab5cc9bb08d or on the readme: https://github.com/MMathisLab/Docker4DeepLabCut2.0#docker-quick-tips

**Comment by MMathisLab** [comment]
then your call to build it is incorrect if it immediately crashes. Check: #GPU, your $HOME binding, etc 

Options:

change port: (i.e. 2351 can be 777, etc)
change which GPU to use (check which GPU you want to use in the terminal by running nvidia-smi)
change the name: --name containername can be anything you want
change the home fodler:-e USER_HOME=$HOME/DeepLabCut (i.e. this can be -e USER_HOME=$HOME/whateveryouwant)

`GPU=1 bash ./dlc-docker run -d -p 2351:8888 -e USER_HOME=$HOME/DeepLabCut --name containername dlc_username/dlcdocker`

**Comment by auesro** [comment]
Thanks, solved now.
The $HOME binding was the issue. Apparently "change the home fodler:-e USER_HOME=$HOME/DeepLabCut (i.e. this can be -e USER_HOME=$HOME/whateveryouwant)" cannot actually be whatever you want, but the proper folder in Home where you have your Docker downloaded.

Best,

Augusto

**Comment by MMathisLab** [comment]
Glad that fixed it. 

Sure, it has to be a folder that exists - but it can just be “HOME” it does not need to be to where the docker is downloaded actually.

**Comment by auesro** [comment]
Ok, got it.
Mistake was assuming it would create the folder, so it was not finding it and closing immediately.
Thanks!
