### ISSUE TITLE
tensorflow installed with pip not pip3

### ISSUE THREAD

**Issue by tomgreen66** [MMathisLab/Docker4DeepLabCut2.0#6]
Seems tensorflow is installed with pip not pip3 so all other dependencies are in the python3 version, tensorflow-gpu==1.8 is in just python2.  Probably due to some package pulling in a dependency python3 does have a tensorflow 1.5.0 version so its possible to still run deeplabcut.  Is there a reason for this setup?  Should tensorflow-gpu==1.8 use pip3 to install?

**Comment by MMathisLab** [comment]
Are you sure you are in the Docker, as I don't have python2 in the container....  this does not happen for me? The kernel option is only python3 and when I use the notebook to check, I only have TF1.8
